apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-web-app
  name: go-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web-app
  strategy: {}
  template:
    metadata:
      labels:
        app: go-web-app
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tags }}
        name: go-web-app
        ports:
        - containerPort: 8080
        resources: {}
status: {}